# Generated by Django 2.2.16 on 2021-07-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
