# Generated by Django 2.2.16 on 2021-07-06 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_theme_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='theme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='theme.Theme'),
            preserve_default=False,
        ),
    ]
