# Generated by Django 2.2.16 on 2021-07-06 06:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('theme', '0004_auto_20210706_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='currentHint',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint10',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint11',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint12',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint13',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint14',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint15',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint16',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint17',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint18',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint19',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint2',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint20',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint21',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint22',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint23',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint24',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint25',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint26',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint27',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint28',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint29',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint3',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint30',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint31',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint32',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint33',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint34',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint35',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint36',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint37',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint38',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint39',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint4',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint40',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint41',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint42',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint43',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint44',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint45',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint46',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint47',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint48',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint49',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint5',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint50',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint51',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint52',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint53',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint54',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint55',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint56',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint57',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint58',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint59',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint6',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint60',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint61',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint62',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint63',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint64',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint65',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint66',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint67',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint68',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint69',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint7',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint70',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint71',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint72',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint73',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint74',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint75',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint76',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint77',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint78',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint79',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint8',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint80',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint9',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='manyHint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='roomEscape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint10',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint11',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint12',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint13',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint14',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint15',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint16',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint17',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint18',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint19',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint2',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint20',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint21',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint22',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint23',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint24',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint25',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint26',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint27',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint28',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint29',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint3',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint30',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint31',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint32',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint33',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint34',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint35',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint36',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint37',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint38',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint39',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint4',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint40',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint41',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint42',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint43',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint44',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint45',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint46',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint47',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint48',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint49',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint5',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint50',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint51',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint52',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint53',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint54',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint55',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint56',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint57',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint58',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint59',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint6',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint60',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint61',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint62',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint63',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint64',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint65',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint66',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint67',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint68',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint69',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint7',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint70',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint71',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint72',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint73',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint74',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint75',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint76',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint77',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint78',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint79',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint8',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint80',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint9',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint10',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint11',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint12',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint13',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint14',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint15',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint16',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint17',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint18',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint19',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint20',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint21',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint22',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint23',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint24',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint25',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint26',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint27',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint28',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint29',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint30',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint31',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint32',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint33',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint34',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint35',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint36',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint37',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint38',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint39',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint40',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint41',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint42',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint43',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint44',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint45',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint46',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint47',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint48',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint49',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint5',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint50',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint51',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint52',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint53',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint54',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint55',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint56',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint57',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint58',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint59',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint6',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint60',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint61',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint62',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint63',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint64',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint65',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint66',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint67',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint68',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint69',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint7',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint70',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint71',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint72',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint73',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint74',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint75',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint76',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint77',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint78',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint79',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint8',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint80',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint9',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint10',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint11',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint12',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint13',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint14',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint15',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint16',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint17',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint18',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint19',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint20',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint21',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint22',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint23',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint24',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint25',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint26',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint27',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint28',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint29',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint30',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint31',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint32',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint33',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint34',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint35',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint36',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint37',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint38',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint39',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint40',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint41',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint42',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint43',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint44',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint45',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint46',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint47',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint48',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint49',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint5',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint50',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint51',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint52',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint53',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint54',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint55',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint56',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint57',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint58',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint59',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint6',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint60',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint61',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint62',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint63',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint64',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint65',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint66',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint67',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint68',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint69',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint7',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint70',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint71',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint72',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint73',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint74',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint75',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint76',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint77',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint78',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint79',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint8',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint80',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint9',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='timer',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='currentCount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='enterKey',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hintCount',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
