# Generated by Django 2.2.16 on 2021-07-08 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_auto_20210706_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='roomEscape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='accounts.Profile'),
        ),
    ]
