# Generated by Django 2.2.16 on 2021-07-14 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(blank=True, choices=[('Korea', 'Korea'), ('Japan', 'Japan'), ('China', 'China')], max_length=30, null=True)),
                ('escape_room', models.CharField(max_length=30)),
                ('reset', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('textHint', models.BooleanField(default=True)),
                ('answer', models.BooleanField(default=False)),
                ('money', models.CharField(blank=True, max_length=30, null=True)),
                ('timer', models.BooleanField(default=False)),
                ('pause', models.BooleanField(default=False)),
                ('onlyCode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
